package com.fractals;

import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;

import javax.imageio.ImageIO;

/**
 * FractalTree --- Represents a 2D Fractal Tree generated by creating two smaller children
 * 				   with a specified angle between them for each existing node every iteration.
 * @author Scott Wolfskill
 * @created     02/12/2019
 * @last_edit   02/12/2019
 */
public class FractalTree extends Fractal2D
{
	protected double angle;		      //angle (radians) created between existing line segment
	protected double scalingFactor;	  //factor to scale line segment length by each iteration
	
	private static double initialSegmentLengthFactor = 0.20; //set initial segmentLength to be 20% of usableHeight's value
	private static double initialAngle_deg = 90; //initial angle (degrees) of the 1st line segment
	
	/**
	 * Creates a non-generated FractalTree with specified parameters.
	 * @param width Width of the image to generate.
	 * @param height Height of the image to generate.
	 * @param iterations Number of fractal iterations to perform.
	 * @param angle Angle in radians between child nodes in the fractal.
	 * @param scalingFactor Scaling factor for each child node in the fractal.
	 * @param padding_horizontal Horizontal padding in the image to generate.
	 * @param padding_vertical Vertical padding in the image to generate.
	 */
	public FractalTree(int width, int height, int iterations, double angle, 
					   double scalingFactor, int padding_horizontal, int padding_vertical)
	{
		this.width = width;
		this.height = height;
		this.totalIterations = iterations;
		this.angle = angle;
		this.scalingFactor = scalingFactor;
		this.padding_horizontal = padding_horizontal;
		this.padding_vertical = padding_vertical;
		image = null;
		gfx = null;
	}
	
	/**
	 * Generates the fractal on image by running for totalIterations iterations.
	 */
	public void generate()
	{
		//Set segmentLength to be a percent factor of the total usable height
		//(taking into account padding on both top and bottom)
		int usableHeight = height - 2 * padding_vertical;
		double segmentLength = initialSegmentLengthFactor * usableHeight;
		
		double startX = width / 2;
		double startY = height - padding_vertical;
		double endX = startX;
		double endY = startY - segmentLength;
		double startAngle = Math.toRadians(initialAngle_deg);
		image = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
		gfx = image.createGraphics();
		iterate(startX, startY, endX, endY, startAngle, segmentLength, totalIterations); //begin iterating (iterationsRemaining) times
	}
	
	private void iterate(double startX, double startY, double endX, double endY, double currAngle, double segmentLength, int iterationsRemaining)
	{
		
		if(iterationsRemaining == 0) {
			return;
		}
		if(segmentLength <= 0) {
			System.out.println("FractalTree.iterate: segmentLength (" + segmentLength + ") became too small! ");
			return;
		}
		//1. Draw single parent line segment
		drawLine(startX, startY, endX, endY);
		
		//2. Calculate endpoints of left and right child nodes
		double childSegmentLength = scalingFactor * segmentLength;
		double lchild_angle = currAngle + angle / 2;
		double lchild_endX = endX + childSegmentLength * Math.cos(lchild_angle);
		double lchild_endY = endY - childSegmentLength * Math.sin(lchild_angle);
		
		double rchild_angle = currAngle - angle / 2;
		double rchild_endX = endX + childSegmentLength * Math.cos(rchild_angle);
		double rchild_endY = endY - childSegmentLength * Math.sin(rchild_angle);
		
		//3. Call iterate on each child recursively
		iterate(endX, endY, lchild_endX, lchild_endY, lchild_angle, childSegmentLength, iterationsRemaining - 1); //left child
		iterate(endX, endY, rchild_endX, rchild_endY, rchild_angle, childSegmentLength, iterationsRemaining - 1); //right child
	}
	
}
